USE [GlobalReach]
GO

/****** Quick Structure 09/01/2015 13:22:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[data](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[a1] [nvarchar](250) NULL,
	[a2] [nvarchar](250) NULL,
	[a3] [nvarchar](250) NULL,
	[a4] [nvarchar](250) NULL,
	[a5] [nvarchar](250) NULL,
	[a6] [nvarchar](250) NULL,
	[a7] [nvarchar](250) NULL,
	[a8] [nvarchar](250) NULL,
	[a9] [nvarchar](250) NULL,
	[b1] [nvarchar](250) NULL,
	[b2] [nvarchar](250) NULL,
	[b3] [nvarchar](250) NULL,
	[b4] [nvarchar](250) NULL,
	[b5] [nvarchar](250) NULL,
	[b6] [nvarchar](250) NULL,
	[b7] [nvarchar](250) NULL,
	[b8] [nvarchar](250) NULL,
	[b9] [nvarchar](250) NULL,
	[c1] [nvarchar](250) NULL,
	[c2] [nvarchar](250) NULL,
	[c3] [nvarchar](250) NULL,
	[c4] [nvarchar](250) NULL,
	[c5] [nvarchar](250) NULL,
	[c6] [nvarchar](250) NULL,
	[c7] [nvarchar](250) NULL,
	[c8] [nvarchar](250) NULL,
	[c9] [nvarchar](250) NULL,
	[d1] [nvarchar](250) NULL,
	[d2] [nvarchar](250) NULL,
	[d3] [nvarchar](250) NULL,
	[d4] [nvarchar](250) NULL,
	[d5] [nvarchar](250) NULL,
	[d6] [nvarchar](250) NULL,
	[d7] [nvarchar](250) NULL
) ON [PRIMARY]

GO