perl C:\JETT-VDP\1seperator.pl
perl C:\JETT-VDP\USA-DL-INSERT.pl

perl C:\JETT-VDP\USA-MovieA4.pl

perl C:\JETT-VDP\USA-Movie-C5-v2.pl

perl C:\JETT-VDP\USA-Movie-POSTER.pl

perl C:\JETT-VDP\UK-DL-INSERT.pl

perl C:\JETT-VDP\UK-MovieA4.pl

perl C:\JETT-VDP\UK-Movie-C5-v2.pl

perl C:\JETT-VDP\UK-Movie-POSTER.pl

perl C:\JETT-VDP\ukINVOICING.pl
perl C:\JETT-VDP\usaINVOICING.pl
perl C:\JETT-VDP\seperator.pl